Oes:
  activerecord:
    models:
      user: "usuario"
    attributes:
      user:
        username: "Ese nombre de usuario"
        password: "Contraseña"
        password_confirmation: "Repite contraseña"
        question: "La pregunta"
        answer: "La espuesta"
  profile: "Paso 1: Encuesta"
  report: "Paso 3: Consumo"
  invoices: "Paso 2: Facturas"

  login: "Identificarse"
  email: "Email"
  password: "Contraseña"
  sign_in: "Entrar"
  sign_up: "Registrarme"
  forgot_password: "Olvidé la contraseña"
  remember_me: "Recordarme en este equipo"

  session:
    close: "Salir"

         



       

       
     