es:
  disable_with: "Por favor, espere..."
  username: "Usuario"
  password: "Contraseña"
  password_confirmation: "Repite"
  login: "Entrar"
  question: "Pregunta"
  answer: "Respuesta"
  submit_create_user: "Dar de alta"
  user:
    login: "Entrar en la zona de usuarios"
    new_user: "Dar de alta un nuevo usuario"
  admin:
    login: "Entrar a la sección de administración"
    session_closed: "No estás autenticado como adminstrador"
    session_close: "Salir de la sección de administración"
    users: "Usuarios registrados"
    development: "Evolución de E3E"
    statistics: "Estadísticas"
  invoices:
    gas: "Consumo de gas"
    elec: "Consumo eléctrico"
